import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEader */}
      <Header />
      <main>
        {/* SIdebar */}
        {/* feed */}
        {/* Widgets */}
      </main>
    </div>
  );
}
